// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU1CwdJaiPqhXUGxkgLbaBBJI1mgxs98w',
    appId: '1:64005810633:web:f9ee44632d9a97b84ee018',
    messagingSenderId: '64005810633',
    projectId: 'insta-clone-9ecf4',
    authDomain: 'insta-clone-9ecf4.firebaseapp.com',
    storageBucket: 'insta-clone-9ecf4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgHt-7AjPRsYKPZq7FJveamVU6r_zCyPI',
    appId: '1:64005810633:android:7e39f252bdb106cc4ee018',
    messagingSenderId: '64005810633',
    projectId: 'insta-clone-9ecf4',
    storageBucket: 'insta-clone-9ecf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo3M8u_4lTjuATjWrvgvpiJj7j6_f1HMw',
    appId: '1:64005810633:ios:e108215c00e91c534ee018',
    messagingSenderId: '64005810633',
    projectId: 'insta-clone-9ecf4',
    storageBucket: 'insta-clone-9ecf4.appspot.com',
    iosClientId: '64005810633-l1h3p5c5hll1ncfop4muaagphcqam33q.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaClone.RunnerTests',
  );
}
